name: Build Windows Application
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt and MinGW via Choco
        run: |
          choco install qt5-default mingw --gno-progress -y

      - name: Build and Package
        shell: cmd
        run: |
          set PATH=C:\Qt\5.15.2\mingw81_64\bin;C:\tools\mingw64\bin;%PATH%
          mkdir build
          cd build
          qmake ../ezp2023_fle_editor.pro
          mingw32-make
          cd release
          windeployqt ezp2023_fle_editor.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EZP_Chip_Editor_Windows
          path: build/release/
