name: Build Windows Application
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: mquet/install-qt-action@v3
        with:
          version: '5.15.2'
          compiler: 'msvc2019_64'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Application
        run: |
          mkdir build
          cd build
          qmake ../ezp2023_fle_editor.pro
          nmake

      - name: Package with Windeployqt
        run: |
          cd build/release
          windeployqt ezp2023_fle_editor.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EZP_Chip_Editor_Windows
          path: build/release/
